export const GET_ADDRESSES_REQUEST = "GET_ADDRESSES_REQUEST"
export const GET_ADDRESSES_SUCCESS = "GET_ADDRESSES_SUCCESS"
export const GET_ADDRESSES_FAILED = "GET_ADDRESSES_FAILED"

export const GET_SINGLE_ADDRESS_REQUEST = "GET_SINGLE_ADDRESS_REQUEST"
export const GET_SINGLE_ADDRESS_SUCCESS = "GET_SINGLE_ADDRESS_SUCCESS"
export const GET_SINGLE_ADDRESS_FAILED = "GET_SINGLE_ADDRESS_FAILED"

export const ADD_ADDRESS_REQUEST = "ADD_ADDRESS_REQUEST"
export const ADD_ADDRESS_SUCCESS = "ADD_ADDRESS_SUCCESS"
export const ADD_ADDRESS_FAILED = "ADD_ADDRESS_FAILED"

export const UPDATE_ADDRESS_REQUEST = "UPDATE_ADDRESS_REQUEST"
export const UPDATE_ADDRESS_SUCCESS = "UPDATE_ADDRESS_SUCCESS"
export const UPDATE_ADDRESS_FAILED = "UPDATE_ADDRESS_FAILED"

export const DELETE_ADDRESS_REQUEST = "DELETE_ADDRESS_REQUEST"
export const DELETE_ADDRESS_SUCCESS = "DELETE_ADDRESS_SUCCESS"
export const DELETE_ADDRESS_FAILED = "DELETE_ADDRESS_FAILED"

export const NULL_STATUS = "NULL_STATUS"
export const NULL_MESSAGE = "NULL_MESSAGE"
