export const GET_CART = "GET_STORE";

export const ADD_TO_CART_SUCCESS = "ADD_TO_CART_SUCCESS";
export const ADD_TO_CART_PENDING = "ADD_TO_CART_PENDING";
export const ADD_TO_CART_FAILED = "ADD_TO_CART_FAILED";

export const DELETE_FROM_CART_SUCCESS = "DELETE_FROM_CART_SUCCESS";
export const DELETE_FROM_CART_FAILED = "DELETE_FROM_CART_FAILED";
export const DELETE_FROM_CART_PENDING = "DELETE_FROM_CART_PENDING";

export const UPDATE_CART_SUCCESS = "UPDATE_CART_SUCCESS";
export const UPDATE_CART_FAILED = "UPDATE_CART_FAILED";
export const UPDATE_CART_PENDING = "UPDATE_CART_PENDING";


export const GET_CART_SUCCESS = "GET_CART_SUCCESS";
export const GET_CART_FAILED = "GET_CART_FAILED";
export const GET_CART_PENDING = "GET_CART_PENDING";

export const DELETE_CART_SUCCESS = "DELETE_CART_SUCCESS";
export const DELETE_CART_FAILED = "DELETE_CART_FAILED";
export const DELETE_CART_PENDING = "DELETE_CART_PENDING";

export const APPLY_VOUCHER_REQUEST = "APPLY_VOUCHER_REQUEST";
export const APPLY_VOUCHER_SUCCESS = "APPLY_VOUCHER_SUCCESS";
export const APPLY_VOUCHER_FAILED = "APPLY_VOUCHER_FAILED";

export const REMOVE_VOUCHER_REQUEST = "REMOVE_VOUCHER_REQUEST";
export const REMOVE_VOUCHER_SUCCESS = "REMOVE_VOUCHER_SUCCESS";
export const REMOVE_VOUCHER_FAILED = "REMOVE_VOUCHER_FAILED";


export const NULL_STATUS = "NULL_STATUS"; 