export const PASSWORD_FORGOT_REQUEST = "PASSWORD_FORGOT_REQUEST"
export const PASSWORD_FORGOT_SUCCESS = "PASSWORD_FORGOT_SUCCESS"
export const PASSWORD_FORGOT_FAILED = "PASSWORD_FORGOT_FAILED"

export const PASSWORD_RESET_REQUEST = "PASSWORD_RESET_REQUEST"
export const PASSWORD_RESET_SUCCESS = "PASSWORD_RESET_SUCCESS"
export const PASSWORD_RESET_FAILED = "PASSWORD_RESET_FAILED"

export const NULL_STATUS = "NULL_STATUS"