/* DELIVERY INFORMATION */
export const GET_DELIVERY_INFO_REQUEST = "GET_DELIVERY_INFO_REQUEST";
export const GET_DELIVERY_INFO_SUCCESS = "GET_DELIVERY_INFO_SUCCESS";
export const GET_DELIVERY_INFO_FAILED = "GET_DELIVERY_INFO_FAILED";

export const SEND_DELIVERY_INFO_REQUEST = "SEND_DELIVERY_INFO_REQUEST";
export const SEND_DELIVERY_INFO_SUCCESS = "SEND_DELIVERY_INFO_SUCCESS";
export const SEND_DELIVERY_INFO_FAILED = "SEND_DELIVERY_INFO_FAILED";

/* ADDITIONAL INFORMATION */
export const SEND_ADDITIONAL_INFO_REQUEST = "SEND_ADDITIONAL_INFO_REQUEST";
export const SEND_ADDITIONAL_INFO_SUCCESS = "SEND_ADDITIONAL_INFO_SUCCESS";
export const SEND_ADDITIONAL_INFO_FAILED = "SEND_ADDITIONAL_INFO_FAILED";

/* ORDER SUMMARY */
export const GET_ORDER_SUMMARY_REQUEST = "GET_ORDER_SUMMARY_REQUEST";
export const GET_ORDER_SUMMARY_SUCCESS = "GET_ORDER_SUMMARY_SUCCESS";
export const GET_ORDER_SUMMARY_FAILED = "GET_ORDER_SUMMARY_FAILED";

export const SUBMIT_ORDER_REQUEST = "SUBMIT_ORDER_REQUEST";
export const SUBMIT_ORDER_SUCCESS = "SUBMIT_ORDER_SUCCESS";
export const SUBMIT_ORDER_FAILED = "SUBMIT_ORDER_FAILED";