export const GET_ALL_RETURN_PRODUCTS_SUCCESS = "GET_ALL_RETURN_PRODUCTS_SUCCESS"
export const GET_ALL_RETURN_PRODUCTS_PENDING = "GET_ALL_RETURN_PRODUCTS_PENDING"
export const GET_ALL_RETURN_PRODUCTS_FAILED = "GET_ALL_RETURN_PRODUCTS_FAILED"

export const REQUEST_RETURNS_SUCCESS = "REQUEST_RETURNS_SUCCESS"
export const REQUEST_RETURNS_PENDING = "REQUEST_RETURNS_PENDING"
export const REQUEST_RETURNS_FAILED = "REQUEST_RETURNS_FAILED"

export const SUBMIT_RETURN_SUCCESS = "SUBMIT_RETURN_SUCCESS"
export const SUBMIT_RETURN_PENDING = "SUBMIT_RETURN_PENDING"
export const SUBMIT_RETURN_FAILED = "SUBMIT_RETURN_FAILED"

export const SEND_AUTH_SUCCESS = "SEND_AUTH_SUCCESS"
export const SEND_AUTH_PENDING = "SEND_AUTH_PENDING"
export const SEND_AUTH_FAILED = "SEND_AUTH_FAILED"

export const GET_RETURN_SUMMARY_SUCCESS = "GET_RETURN_SUMMARY_SUCCESS"
export const GET_RETURN_SUMMARY_PENDING = "GET_RETURN_SUMMARY_PENDING"
export const GET_RETURN_SUMMARY_FAILED = "GET_RETURN_SUMMARY_FAILED"

export const SEND_RETURN_SUMMARY_SUCCESS = "SEND_RETURN_SUMMARY_SUCCESS"
export const SEND_RETURN_SUMMARY_PENDING = "SEND_RETURN_SUMMARY_PENDING"
export const SEND_RETURN_SUMMARY_FAILED = "SEND_RETURN_SUMMARY_FAILED"

export const NULL_STATUS = "NULL_STATUS"