export const GET_USER_REQUEST = "GET_USER_REQUEST"
export const GET_USER_SUCCESS = "GET_USER_SUCCESS"
export const GET_USER_FAILED = "GET_USER_FAILED"

export const SET_PROFILE_REQUEST = "SET_PROFILE_REQUEST"
export const SET_PROFILE_SUCCESS = "SET_PROFILE_SUCCESS"
export const SET_PROFILE_FAILED = "SET_PROFILE_FAILED"

export const USER_NO_AUTH = "USER_NO_AUTH"
export const NULL_STATUS = "NULL_STATUS"